# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

- name: "Create user '{{ username }}'"
  become: yes
  user:
    name: "{{ username }}"
    state: present
    groups: docker, wheel
    password: "{{ password }}"

- name: "Check that file {{ authorized_keys_file }} exists"
  local_action: stat path="{{ playbook_dir }}/{{ authorized_keys_file }}"
  register: p
- debug:
    msg: "Please add public ssh keys to the file: {{ playbook_dir }}/{{ authorized_keys_file }}"
  when: not p.stat.exists
  failed_when: not p.stat.exists

- name: "Enable ssh access for users defined above"
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', playbook_dir + '/' + authorized_keys_file) }}"
