#
# Example docker stack file for FlowTrigger
# Note: The flowtrigger container would need to be connected to a network on which the FlowAPI URL is accessible.
#

version: '3.7'

secrets:
  FLOWTRIGGER_DB_PASSWORD: # Password for FlowTrigger's database
    external: true
  FLOWAPI_TOKEN: # Token for FlowTrigger to connect to FlowAPI
    external: true

networks:
  database:

services:

  flowtrigger:
    image: flowminder/flowtrigger:${CONTAINER_TAG:-latest}
    environment:
      FLOWTRIGGER_INPUTS_DIR: /mounts/inputs
      FLOWTRIGGER_OUTPUTS_DIR: /mounts/outputs
      FLOWTRIGGER_LOG_LEVEL: ${FLOWTRIGGER_LOG_LEVEL:-ERROR}
      FLOWTRIGGER_DB_URI: postgresql://flowtrigger:{}@flowtrigger_postgres:5432/flowtrigger
      FLOWAPI_URL: ${FLOWAPI_URL:?Must set FLOWAPI_URL env var}
    secrets:
      - FLOWTRIGGER_DB_PASSWORD
      - FLOWAPI_TOKEN
    volumes:
      - ${FLOWTRIGGER_INPUTS_DIR:?Must set FLOWTRIGGER_INPUTS_DIR env var}:/mounts/inputs:ro
      - ${FLOWTRIGGER_OUTPUTS_DIR:?Must set FLOWTRIGGER_OUTPUTS_DIR env var}:/mounts/outputs:rw
    networks:
      - database
  
  flowtrigger_postgres:
    image: postgres
    tty: true
    stdin_open: true
    environment:
      POSTGRES_USER: flowtrigger
      POSTGRES_PASSWORD_FILE: /run/secrets/FLOWTRIGGER_DB_PASSWORD
      POSTGRES_DB: flowtrigger
    secrets:
      - FLOWTRIGGER_DB_PASSWORD
    networks:
      - database
