flowapi_url = "$FLOWAPI_URL"
db_uri = "$AUTOFLOW_DB_URI"

[inputs]

inputs_dir = "$AUTOFLOW_INPUTS_DIR"

[outputs]

notebooks_dir = "$AUTOFLOW_OUTPUTS_DIR/notebooks"
reports_dir = "$AUTOFLOW_OUTPUTS_DIR/reports"

[logging]

level = "$AUTOFLOW_LOG_LEVEL"
