asciidoc_template_path = "$AUTOMATION_CONFIG_DIR/asciidoc_extended.tpl"
flowapi_url = "$FLOWAPI_URL"
db_uri = "$AUTOMATION_DB_URI"

[inputs]

inputs_dir = "$AUTOMATION_INPUTS_DIR"

[outputs]

notebooks_dir = "$AUTOMATION_OUTPUTS_DIR/notebooks"
reports_dir = "$AUTOMATION_OUTPUTS_DIR/reports"

[logging]

level = "$AUTOMATION_LOG_LEVEL"
