queue_rules:
  - name: duplicated default from automatic merge for Dependabot pull requests on
      master
    queue_conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
      - status-success=run_build_pipeline
      - author=dependabot[bot]
      - status-success=run_build_pipeline
      - base=master
    merge_conditions: []
    merge_method: merge
  - name: default
    queue_conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
      - status-success=run_build_pipeline
    merge_conditions:
      - status-success=run_build_pipeline
      - base=master
    merge_method: merge

pull_request_rules:
  - name: Automatic merge for approved PRs labelled as ready + automatic merge for
      Dependabot pull requests on master
    conditions: []
    actions:
      queue:
