queue_rules:
  - name: default
    conditions:
      - status-success=run_build_pipeline
      - base=master


pull_request_rules:
  - name: Automatic merge for approved PRs labelled as ready
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
      - status-success=run_build_pipeline
    actions:
      queue:
        name: default
        method: merge

  - name: automatic merge for Dependabot pull requests on master
    conditions:
      - author=dependabot[bot]
      - status-success=run_build_pipeline
      - base=master
    actions:
      queue:
        name: default
        method: merge

