pull_request_rules:
  - name: Automatic merge for approved PRs labelled as ready
    conditions:
        - "#approved-reviews-by>=1"
        - label=ready-to-merge
        - status-success=run_build_pipeline
        - base=master
    actions:
        merge:
            method: rebase
  - name: Automatic merge for Dependabot pull requests
    conditions:
        - author=dependabot[bot]
        - status-success=run_build_pipeline
        - base=master
    actions:
        merge:
            method: rebase
