dist: xenial
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"  # 3.8 development branch
  - "pypy3.5" # Pypy
# command to install dependencies
before_install:
  - cd flowclient
install:
  - pip install .
# command to run tests
script:
  - pytest