# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# DOCKER COMPOSE FOR FLOWKIT SYNTHETIC DATA
#

version: '3.5'

networks:
  db:


services:

  flowdb_synthetic_data:
    container_name: flowdb_synthetic_data
    image: flowminder/flowdb-synthetic-data:${CONTAINER_TAG:-latest}
    ports:
      - ${FLOWDB_PORT:?Must set FLOWDB_PORT env var}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Must set POSTGRES_USER env var}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Must set POSTGRES_PASSWORD env var}
      FLOWMACHINE_FLOWDB_USER: ${FLOWMACHINE_FLOWDB_USER:?Must set FLOWMACHINE_FLOWDB_USER env var}
      FLOWMACHINE_FLOWDB_PASSWORD: ${FLOWMACHINE_FLOWDB_PASSWORD:?Must set FLOWMACHINE_FLOWDB_PASSWORD env var}
      FLOWAPI_FLOWDB_USER: ${FLOWAPI_FLOWDB_USER:?Must set FLOWAPI_FLOWDB_USER env var}
      FLOWAPI_FLOWDB_PASSWORD: ${FLOWAPI_FLOWDB_PASSWORD:?Must set FLOWAPI_FLOWDB_PASSWORD env var}
      CACHE_SIZE: ${CACHE_SIZE:-""}
      CACHE_HALF_LIFE: ${CACHE_HALF_LIFE:?Must set CACHE_HALF_LIFE env var}
      FLOWDB_ENABLE_POSTGRES_DEBUG_MODE: ${FLOWDB_ENABLE_POSTGRES_DEBUG_MODE:?Must set FLOWDB_ENABLE_POSTGRES_DEBUG_MODE env var}
      SYNTHETIC_DATA_GENERATOR: ${SYNTHETIC_DATA_GENERATOR:?Must set SYNTHETIC_DATA_GENERATOR env var}
      N_SITES: ${N_SITES:?Must set N_SITES env var}
      N_CELLS: ${N_CELLS:?Must set N_CELLS env var}
      N_SUBSCRIBERS: ${N_SUBSCRIBERS:?Must set N_SUBSCRIBERS env var}
      N_DAYS: ${N_DAYS:?Must set N_DAYS env var}
      N_CALLS: ${N_CALLS:?Must set N_CALLS env var}
      N_SMS: ${N_SMS:?Must set N_SMS env var}
      N_MDS: ${N_MDS:?Must set N_MDS env var}
      N_TACS: ${N_TACS:?Must set N_TACS env var}
      P_OUT_OF_AREA: ${P_OUT_OF_AREA:?Must set P_OUT_OF_AREA env var}
      P_RELOCATE: ${P_RELOCATE:?Must set P_RELOCATE env var}
      INTERACTIONS_MULTIPLIER: ${INTERACTIONS_MULTIPLIER:?Must set INTERACTIONS_MULTIPLIER env var}
      DISASTER_START: ${DISASTER_START:?Must set DISASTER_START env var}
      DISASTER_END: ${DISASTER_END:?Must set DISASTER_END env var}
    shm_size: 1G
    tty: true
    stdin_open: true
    restart: always
    networks:
      db:
        aliases:
          - flowdb
