# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# DOCKER COMPOSE BUILDER FOR FLOWKIT
#

version: '3.5'

services:
  flowdb:
    image: flowminder/flowdb-testdata:${CONTAINER_TAG:-latest}
    build:
      context: .
      dockerfile: flowdb_testdata.Dockerfile
