# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# DOCKER COMPOSE FOR FLOWKIT SYNTHETIC DATA
#

version: '3.5'

services:

  flowdb:
    container_name: flowdb
    image: flowminder/flowdb-synthetic-data:${CONTAINER_TAG:-latest}
    environment:
      SYNTHETIC_DATA_GENERATOR: ${SYNTHETIC_DATA_GENERATOR:?Must set SYNTHETIC_DATA_GENERATOR env var}
      COUNTRY: ${COUNTRY:-NPL}
      N_SITES: ${N_SITES:?Must set N_SITES env var}
      N_CELLS: ${N_CELLS:?Must set N_CELLS env var}
      N_SUBSCRIBERS: ${N_SUBSCRIBERS:?Must set N_SUBSCRIBERS env var}
      N_DAYS: ${N_DAYS:?Must set N_DAYS env var}
      N_CALLS: ${N_CALLS:?Must set N_CALLS env var}
      N_SMS: ${N_SMS:?Must set N_SMS env var}
      N_MDS: ${N_MDS:?Must set N_MDS env var}
      N_TACS: ${N_TACS:?Must set N_TACS env var}
      P_OUT_OF_AREA: ${P_OUT_OF_AREA:?Must set P_OUT_OF_AREA env var}
      P_RELOCATE: ${P_RELOCATE:?Must set P_RELOCATE env var}
      INTERACTIONS_MULTIPLIER: ${INTERACTIONS_MULTIPLIER:?Must set INTERACTIONS_MULTIPLIER env var}
      DISASTER_START: ${DISASTER_START:?Must set DISASTER_START env var}
      DISASTER_END: ${DISASTER_END:?Must set DISASTER_END env var}
      DISASTER_REGION_PCOD: ${DISASTER_REGION_PCOD:-NPL.1.1_1}
      PARQUET_FOLDER: ${PARQUET_FOLDER:?Must set PARQUET_FOLDER env var}
    # DEV MOUNT remove before merge
    volumes:
            - "./flowdb/testdata/test_data/py:/docker-entrypoint-initdb.d/py/testdata/"
            - type: bind
              source: $PARQUET_FOLDER
              destination: "/parquet_files"

