default_args:
  owner: flowminder
  start_date: '1900-01-01'
etl:
  calls:
    concurrency: 4
    source:
      source_type: sql
      table_name: "sample_data_fdw"
      event_time_column: "event_time"
  sms:
    concurrency: 2
    source:
      source_type: csv
      filename_pattern: SMS_(\d{8}).csv
