asciidoc_template_path = "$FLOWTRIGGER_CONFIG_DIR/asciidoc_extended.tpl"
flowapi_url = "$FLOWAPI_URL"
db_uri = "$FLOWTRIGGER_DB_URI"

[inputs]

inputs_dir = "$FLOWTRIGGER_INPUTS_DIR"

[outputs]

notebooks_dir = "$FLOWTRIGGER_OUTPUTS_DIR/notebooks"
reports_dir = "$FLOWTRIGGER_OUTPUTS_DIR/reports"

[logging]

level = "$FLOWTRIGGER_LOG_LEVEL"
