#
# DOCKER COMPOSE FOR FLOWDB WITH PG_HERO
#
# Note: some of the environment variables used in this file
#       have default values which are defined in the .env file
#       in this directory.

version: '2'

services:
  pg-hero:
        container_name: ${PG_HERO_CONTAINER_NAME}
        image: bmorton/pghero:latest
        ports:
            - ${PG_HERO_PORT}:8080
        environment:
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${FLOWDB_CONTAINER_NAME}:5432/flowdb