#
# DOCKER COMPOSE FOR FLOWDB
#
# Note: some of the environment variables used in this file
#       have default values which are defined in the .env file
#       in this directory.

version: '2'

services:
    flowdb:
        container_name: '${FLOWDB_CONTAINER_NAME}'
        image: flowminder/flowdb:${FLOWDB_VERSION}
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - FM_PASSWORD=${FM_PASSWORD}
            - API_PASSWORD=${API_PASSWORD}
            - LOCATION_TABLE=${LOCATION_TABLE}
        ports:
            - "${FLOWDB_PORT}:5432"
        tty: true
        stdin_open: true
        restart: always
        volumes:
            - ${FLOWDB_DATA_DIR}:/var/lib/postgresql/data
            - ${FLOWDB_INGESTION_DIR}:/ingestion
