# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
- hosts: all
  vars:
    username: flowkit
    password: "$6$YaOatFoRa91eOA06$cLJCvJCdd0sLKBEM01eQ2wJ7ZKkTZJz.YWGFK5r0bs4yqiwAz1Lw9pmExiS.PPBBJv13cuBpiHYU88ThX4TeG/"
    pyenv_path: "/usr/local/pyenv"
    pyenv_global_python_version: "3.7.3"
  roles:
    - base_packages
    - docker
    - role: user_accounts
      username: "{{ username }}"
      password: "{{ password }}"
    - role: avanov.pyenv
      pyenv_env: "system"
      pyenv_owner: "{{ ansible_user }}"
      pyenv_global: "{{ pyenv_global_python_version }}"
      pyenv_python_versions:
       - "{{ pyenv_global_python_version }}"
      pyenv_virtualenvs:
       - venv_name: "v{{ pyenv_global_python_version }}"
         py_version: "{{ pyenv_global_python_version }}"

  tasks:
    - name: "Install pipenv"
      pip:
        name: pipenv
        executable: "{{ pyenv_path }}/shims/pip"
    - name: "Clone FlowKit repo"
      become: yes
      become_user: "{{ username }}"
      git:
        repo: "https://github.com/Flowminder/FlowKit.git"
        dest: "~{{ username }}/code/FlowKit"
        version: master
        update: no
