# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

#
#  FLOWDB
#  -----
#
#
#  Extends the basic FlowDB image to include arbitrary amount of test data.
#
ARG CODE_VERSION=latest
FROM flowminder/flowdb:${CODE_VERSION}

RUN echo "deb http://ftp.de.debian.org/debian testing main" > /etc/apt/sources.list \
        && apt-get -y update \
        && apt-get -y install python3.7 python3.7-distutils python3-psutil \
        && pip3 install pipenv \
        && apt-get clean --yes \
        && apt-get autoclean --yes \
        && apt-get autoremove --yes \
        && rm -rf /var/cache/debconf/*-old \
        && rm -rf /var/lib/apt/lists/*

# Install python dependencies
COPY --chown=postgres ./Pipfile* /tmp/
RUN PIPENV_PIPFILE=/tmp/Pipfile pipenv install --system --deploy --three \
    && rm /tmp/Pipfile*

#
#   Add synthetic data to the ingestion directory.
#
RUN mkdir -p /docker-entrypoint-initdb.d/sql/syntheticdata/ && \
    mkdir -p /opt/synthetic_data/ && \
    mkdir -p /docker-entrypoint-initdb.d/data/records/calls && \
    mkdir -p /docker-entrypoint-initdb.d/data/infrastructure

COPY --chown=postgres ./bin/z_ingest_synthetic_data.sh /docker-entrypoint-initdb.d/

COPY --chown=postgres bin/generate_synthetic_data.py /opt/synthetic_data/
ADD --chown=postgres ./test_data/sql/admin*.sql /docker-entrypoint-initdb.d/sql/syntheticdata/
# Need to make postgres is owner of any subdirectrories
RUN mkdir docker-entrypoint-initdb.d/sql/syntheticdata/sql &&  chown -R postgres /docker-entrypoint-initdb.d
# Need to relax the permissions in case the container is running as an arbitrary user with a bind mount
RUN chmod -R 777 /docker-entrypoint-initdb.d

ENV N_DAYS=7
ENV N_SUBSCRIBERS=4000
ENV N_TACS=1000
ENV N_SITES=1000
ENV N_CELLS=8000
ENV N_CALLS=200000
ENV N_SMS=200000
ENV N_MDS=200000
ENV OUTPUT_ROOT_DIR=/docker-entrypoint-initdb.d
