"""
A dictionary of the columns that will be present in each event CSV type - also serves as a list of
valid event types
"""

event_column_mappings = {
    "call": {
        "MSISDN": "text",
        "IMEI": "text",
        "IMSI": "text",
        "TAC": "text",
        "CELL_ID": "text",
        "DATE_TIME": "timestamptz",
        "EVENT_ID": "int",
        "EVENT_TYPE": "smallint",
        "IS_INCOMING": "bool",
        "OTHER_MSISDN": "text",
        "DURATION": "real",
    },
    "sms": {
        "MSISDN": "text",
        "IMEI": "text",
        "IMSI": "text",
        "TAC": "text",
        "CELL_ID": "text",
        "DATE_TIME": "timestamptz",
        "EVENT_ID": "int",
        "EVENT_TYPE": "smallint",
        "IS_INCOMING": "bool",
        "OTHER_MSISDN": "text",
    },
    "location": {
        "MSISDN": "text",
        "IMEI": "text",
        "IMSI": "text",
        "TAC": "text",
        "CELL_ID": "text",
        "DATE_TIME": "timestamptz",
        "EVENT_ID": "int",
        "EVENT_TYPE": "smallint",
    },
    "mds": {
        "MSISDN": "text",
        "IMEI": "text",
        "IMSI": "text",
        "TAC": "text",
        "CELL_ID": "text",
        "DATE_TIME": "timestamptz",
        "EVENT_ID": "int",
        "EVENT_TYPE": "smallint",
        "DATA_VOLUME_UP": "int",
        "DATA_VOLUME_DOWN": "int",
        "DURATION": "real",
    },
    "topup": {
        "MSISDN": "text",
        "IMEI": "text",
        "IMSI": "text",
        "TAC": "text",
        "CELL_ID": "text",
        "DATE_TIME": "timestamptz",
        "EVENT_ID": "int",
        "EVENT_TYPE": "smallint",
        "RECHARGE_AMOUNT": "real",
        "AIRTIME_FEE": "real",
        "TAX_AND_FEE": "real",
        "PRE_EVENT_BALANCE": "real",
        "POST_EVENT_BALANCE": "real",
    },
}
