#
# Compose file for flowkit integration tests
#

version: "3"

services:
  flowdb:
    container_name: flowkit_docs_flowdb
    image: "flowminder/flowdb-synthetic-data:faster"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-flowdb}
      - POSTGRES_USER=${POSTGRES_USER:-flowdb}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-flowflow}
      - FM_PASSWORD=${FM_PASSWORD:-foo}
      - API_PASSWORD=${API_PASSWORD:-foo}
      - N_SITES=200
      - N_CELLS=1000
      - N_SUBSCRIBERS=50000
      - N_DAYS=60
      - N_CALLS=20000
      - N_SMS=20000
      - N_MDS=100000
    tty: true
    shm_size: 1G
    ports:
      - "$FLOWDB_PORT:5432"
    stdin_open: true
    restart: always
  query_locker:
    container_name: flowkit_docs_redis
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-fm_redis}
    ports:
      - "$REDIS_PORT:6379"
