default_args:
  owner: flowminder
  start_date: '1900-01-01'
etl:
  calls:
    concurrency: 4
    source:
      source_type: csv
      filename_pattern: CALLS_(\d{4}[01]\d[0123]\d).csv.gz
  mds:
    concurrency: 4
    source:
      source_type: csv
      filename_pattern: MDS_(\d{4}[01]\d[0123]\d).csv.gz
  sms:
    concurrency: 4
    source:
      source_type: sql
      table_name: "sms_raw_data_dump"
  topups:
    concurrency: 4
    source:
      source_type: csv
      filename_pattern: TOPUPS_(\d{4}[01]\d[0123]\d).csv.gz
