# This is an example flowetl config file which
# is also used in the flowetl unit tests.
default_args:
  owner: flowminder
  start_date: '1900-01-01'
etl:
  calls:
    concurrency: 4
    source:
      source_type: csv
      filename_pattern: CALLS_(\d{4}[01]\d[0123]\d).csv.gz
  sms:
    concurrency: 4
    source:
      source_type: csv
      filename_pattern: SMS_(\d{4}[01]\d[0123]\d).csv.gz
  mds:
    concurrency: 4
    source:
      source_type: sql
      table_name: "mds_raw_data_dump"
      sql_find_available_dates: |
          SELECT DISTINCT event_time::date as date FROM mds_raw_data_dump
  topups:
    concurrency: 4
    source:
      source_type: csv
      filename_pattern: TOPUPS_(\d{4}[01]\d[0123]\d).csv.gz
