version: '3'

x-flowetl-common:
  &flowetl-common
  image: flowminder/flowetl:${CONTAINER_TAG:-latest}
  restart: always
  tty: true
  stdin_open: true

  volumes:
    - ${HOST_DAGS_DIR:?Must set HOST_DAGS_DIR env var}:/opt/airflow/dags:ro

  environment:
    &flowetl-envs
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${SQL_ALCHEMY_CONN:?Must set SQL_ALCHEMY_CONN env var}
    AIRFLOW_CONN_FLOWDB: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@flowdb:5432/flowdb
    AIRFLOW__CORE__FERNET_KEY: ${FLOWETL_FERNET_KEY:?Must set FLOWETL_FERNET_KEY env var}
    AIRFLOW__CELERY__RESULT_BACKEND: ${CELERY_CONN:?Must set CELERY_CONN env var}
    AIRFLOW__CELERY__BROKER_URL: redis://:@flowetl_redis:6379/0
    POSTGRES_HOST: flowetl_db
    FLOWETL_AIRFLOW_ADMIN_USERNAME: "admin"
    FLOWETL_AIRFLOW_ADMIN_PASSWORD: "password"
    FLOWETL_AIRFLOW_PG_POOL_SLOT_COUNT: 4

  depends_on:
    &flowetl-deps
    flowetl_db:
      condition: service_healthy
    flowetl_redis:
      condition: service_healthy
    flowetl_init:
      condition: service_completed_successfully

networks:
  flowetl:
    driver: bridge
  # Remove later
  flowdb:
    driver: bridge


services:
  flowetl_scheduler:
    << : *flowetl-common
    container_name: flowetl_scheduler
    command: scheduler
    networks:
      - flowetl

  flowetl_db:
    image: postgres:11.0
    container_name: flowetl_db
    tty: true
    stdin_open: true
    restart: always
    ports:
      - ${FLOWETL_POSTGRES_PORT:?Must set FLOWETL_POSTGRES_PORT env var}:5432
    environment:
      POSTGRES_USER: ${FLOWETL_POSTGRES_USER:?Must set FLOWETL_POSTGRES_USER env var}
      POSTGRES_PASSWORD: ${FLOWETL_POSTGRES_PASSWORD:?Must set FLOWETL_POSTGRES_PASSWORD env var}
      POSTGRES_DB: ${FLOWETL_POSTGRES_DB:?Must set FLOWETL_POSTGRES_DB env var}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 30s
      retries: 10
    networks:
      flowetl:
        aliases:
          - flowetl_db

  flowetl_redis:
    container_name: flowetl_redis
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    networks:
      flowetl:
        aliases:
          - flowetl_redis

  flowetl_worker:
    <<: *flowetl-common
    command: celery worker
    deploy:
      replicas: 2
    networks:
      - flowetl
      - flowdb

  flowetl_webserver:
    container_name: flowetl_webserver
    <<: *flowetl-common
    ports:
      - ${FLOWETL_PORT:?Must set FLOWETL_PORT env var}:8080
    command: webserver
    networks:
      - flowetl
    environment:
      <<: *flowetl-envs
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: password

  flowetl_flower:
    container_name: flowetl_flower
    <<: *flowetl-common
    command: celery flower
    ports:
      - ${FLOWETL_CELERY_PORT:?Must set FLOWETL_CELERY_PORT env var}:5555
    restart: always
    networks:
      - flowetl

  flowetl_triggerer:
    container_name: flowetl_triggerer
    <<: *flowetl-common
    command: triggerer
    restart: always
    networks:
      - flowetl

  flowetl_init:
    container_name: flowetl_init
    <<: *flowetl-common
    entrypoint: /bin/bash -c "airflow db init && airflow users create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin"
    networks:
      - flowetl
    depends_on:
      - flowetl_db
      - flowetl_redis
    restart: on-failure


#   Remove after dev is done
  flowdb:
    container_name: flowetl_flowdb
    image: flowminder/flowdb:latest
    networks:
      flowdb:
        aliases:
          - flowdb

