# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# DOCKER COMPOSE FOR FLOWETL COMPONENT OF FLOWKIT
#

version: '3.7'

networks:
  db:
  flowkit_db:
    external: true

services:
  flowetl:
    container_name: flowetl
    image: flowminder/flowetl:${CONTAINER_TAG:-latest}
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 8080:8080

    environment:
      AIRFLOW__CORE__DAGS_FOLDER: /usr/local/airflow/src
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgres://flowetl:flowetl@flowetl_db:5432/flowetl
      AIRFLOW__CORE__FERNET_KEY: ssgBqImdmQamCrM9jNhxI_IXSzvyVIfqvyzES67qqVU=
      POSTGRES_USER: flowetl
      POSTGRES_PASSWORD: flowetl
      POSTGRES_HOST: flowetl_db
      POSTGRES_DB: flowetl
      MOUNT_HOME: /usr/local/mounts

    volumes:
    #   - ${HOST_DAGS_FOLDER}:${AIRFLOW_HOME}/src:rw
    #   - ${HOST_ARCHIVE_DIR}:${MOUNT_HOME}/archive:rw
      - ${HOST_CONFIG_DIR}:${MOUNT_HOME}/config:ro
    #   - ${HOST_DUMP_DIR}:${MOUNT_HOME}/dump:rw
    #   - ${HOST_INGEST_DIR}:${MOUNT_HOME}/ingest:rw
    #   - ${HOST_QUARANTINE_DIR}:${MOUNT_HOME}/quarantine:rw
    #   - ${HOST_REPORTS_DIR}:${MOUNT_HOME}/reports:rw

    networks:
      - flowkit_db
      - db

  flowetl_db:
    # Storage for airflow bookkeeping
    image: postgres:11.0
    container_name: flowetl_db

    tty: true
    stdin_open: true
    restart: always

    volumes:
      - data_volume_flowetl_db:/var/lib/postgresql/data

    ports:
      - 5433:5432
    
    environment:
      POSTGRES_USER: flowetl
      POSTGRES_PASSWORD: flowetl
      POSTGRES_DB: flowetl

    networks:
      - db

volumes:
  data_volume_flowetl_db: