#
# Stack file for flowkit integration tests
#

version: '3.1'
secrets:
  cert-flowkit.pem: # SSL Certificate used to serve FlowAPI over https
    external: true
  FLOWAPI_FLOWDB_USER: # Database user used by FlowAPI
    external: true
  FLOWAPI_FLOWDB_PASS: # Password for the FlowAPI database user
    external: true
  FLOWMACHINE_FLOWDB_USER: # Database user for FlowMachine
    external: true
  FLOWMACHINE_FLOWDB_PASS: # Password for FlowDB
    external: true
  POSTGRES_PASSWORD_FILE: # Postgres superuser password
    external: true
  JWT_SECRET_KEY: # Secret used to sign api tokens
    external: true
  REDIS_PASSWORD_FILE: # Redis password
    external: true
networks:
  db:
  redis:
  zero:
  api:
services:
    flowdb:
        image: "flowminder/flowdb-testdata:${CIRCLE_BRANCH:-latest}"
        secrets:
          - POSTGRES_PASSWORD_FILE
          - FLOWAPI_FLOWDB_USER
          - FLOWAPI_FLOWDB_PASS
          - FLOWMACHINE_FLOWDB_USER
          - FLOWMACHINE_FLOWDB_PASS
        tty: true
        shm_size: 1G
        stdin_open: true
        networks:
          db:
            aliases:
              - flowdb
    flowmachine:
        image: "flowminder/flowmachine:${CIRCLE_BRANCH:-latest}"
        environment:
            - FLOWDB_PORT=5432
            - FLOWDB_HOST=flowdb
            - FLOWMACHINE_LOG_LEVEL=${FLOWMACHINE_LOG_LEVEL:-error}
            - FLOWMACHINE_SERVER_DEBUG_MODE=${FLOWMACHINE_SERVER_DEBUG_MODE:-False}
        secrets:
          - FLOWMACHINE_FLOWDB_USER
          - FLOWMACHINE_FLOWDB_PASS
          - REDIS_PASSWORD_FILE
        networks:
          - db
          - redis
          - zero
    flowapi:
        image: "flowminder/flowapi:${CIRCLE_BRANCH:-latest}"
        ports:
          - "9090:9090"
        environment:
            - FLOWMACHINE_HOST=flowmachine
            - FLOWAPI_LOG_LEVEL=${FLOWAPI_LOG_LEVEL:-error}
            - FLOWDB_HOST=flowdb
        secrets:
          - cert-flowkit.pem
          - JWT_SECRET_KEY
          - FLOWAPI_FLOWDB_USER
          - FLOWAPI_FLOWDB_PASS
        networks:
          - zero
          - db
          - api
    query_locker:
        image: bitnami/redis:latest
        secrets:
          - REDIS_PASSWORD_FILE
        networks:
          redis:
            aliases:
              - redis

