#
# Stack file for flowkit integration tests
#

version: '3.7'
secrets:
  cert-flowkit.pem: # SSL Certificate used to serve FlowAPI over https
    external: true
  FLOWAPI_FLOWDB_USER: # Database user used by FlowAPI
    external: true
  FLOWAPI_FLOWDB_PASSWORD: # Password for the FlowAPI database user
    external: true
  FLOWMACHINE_FLOWDB_USER: # Database user for FlowMachine
    external: true
  FLOWMACHINE_FLOWDB_PASSWORD: # Password for FlowDB
    external: true
  FLOWDB_POSTGRES_PASSWORD: # Postgres superuser password for flowdb
    external: true
  PRIVATE_JWT_SIGNING_KEY: # Secret used to sign api tokens
    external: true
  PUBLIC_JWT_SIGNING_KEY: # Public key to verify api tokens
    external: true
  REDIS_PASSWORD: # Redis password
    external: true
  FLOWAPI_IDENTIFIER: # Secret used in combination with secret key for decoding JWTs, should be unique per FlowAPI server
    external: true
  FLOWAUTH_FERNET_KEY: # Used for encrypted-at-rest storage of tokens in flowauth
    external: true
  FLOWAUTH_ADMIN_USERNAME: # Default flowauth administrator username
    external: true
  FLOWAUTH_ADMIN_PASSWORD: # Default flowauth administrator password
    external: true
  FLOWAUTH_DB_PASSWORD: # Password for flowauth's database
    external: true
networks:
  db:
  redis:
  zero:
  api:
  flowauth_database:
services:
    flowauth:
      image: flowminder/flowauth:${CONTAINER_TAG:-latest}
      ports:
        - "9091:80"
      environment:
        DB_URI: "postgres://flowauth:{}@flowauth_postgres:5432/flowauth"
      secrets:
        - PRIVATE_JWT_SIGNING_KEY
        - FLOWAUTH_FERNET_KEY
        - FLOWAUTH_ADMIN_USERNAME
        - FLOWAUTH_ADMIN_PASSWORD
        - FLOWAUTH_DB_PASSWORD
      networks:
        - flowauth_database

    flowauth_postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD_FILE: /run/secrets/FLOWAUTH_DB_PASSWORD
        POSTGRES_USER: flowauth
        POSTGRES_DB: flowauth
      secrets:
        - FLOWAUTH_DB_PASSWORD
      networks:
        - flowauth_database

    flowdb:
        image: "flowminder/flowdb-testdata:${CONTAINER_TAG:-latest}"
        environment:
          - POSTGRES_PASSWORD_FILE=/run/secrets/FLOWDB_POSTGRES_PASSWORD
        ports:
          - "9000:5432"
        secrets:
          - FLOWDB_POSTGRES_PASSWORD
          - FLOWAPI_FLOWDB_USER
          - FLOWAPI_FLOWDB_PASSWORD
          - FLOWMACHINE_FLOWDB_USER
          - FLOWMACHINE_FLOWDB_PASSWORD
        tty: true
        volumes:
          - type: tmpfs
            target: /dev/shm
            tmpfs:
              size: 1000000000
        stdin_open: true
        networks:
          db:
            aliases:
              - flowdb
    flowmachine:
        image: "flowminder/flowmachine:${CONTAINER_TAG:-latest}"
        environment:
            FLOWDB_PORT: 5432
            FLOWDB_HOST: flowdb
            FLOWMACHINE_LOG_LEVEL: ${FLOWMACHINE_LOG_LEVEL:-error}
            FLOWMACHINE_SERVER_DEBUG_MODE: ${FLOWMACHINE_SERVER_DEBUG_MODE:-False}
            REDIS_HOST: flowmachine_query_locker
        secrets:
          - FLOWMACHINE_FLOWDB_USER
          - FLOWMACHINE_FLOWDB_PASSWORD
          - REDIS_PASSWORD
        networks:
          - db
          - redis
          - zero
    flowapi:
        image: "flowminder/flowapi:${CONTAINER_TAG:-latest}"
        ports:
          - "9090:9090"
        environment:
            FLOWMACHINE_HOST: flowmachine
            FLOWAPI_LOG_LEVEL: ${FLOWAPI_LOG_LEVEL:-error}
            FLOWDB_HOST: flowdb
        secrets:
          - cert-flowkit.pem
          - PUBLIC_JWT_SIGNING_KEY
          - FLOWAPI_FLOWDB_USER
          - FLOWAPI_FLOWDB_PASSWORD
          - FLOWAPI_IDENTIFIER
        networks:
          - zero
          - db
          - api
    flowmachine_query_locker:
        image: bitnami/redis:latest
        environment:
          REDIS_PASSWORD_FILE: /run/secrets/REDIS_PASSWORD
        secrets:
          - REDIS_PASSWORD
        networks:
          redis:
            aliases:
              - redis

