#
# Stack file for flowkit integration tests
#

version: '3.7'
secrets:
  cert-flowkit.pem: # SSL Certificate used to serve FlowAPI over https
    external: true
  FLOWAPI_FLOWDB_USER: # Database user used by FlowAPI
    external: true
  FLOWAPI_FLOWDB_PASSWORD: # Password for the FlowAPI database user
    external: true
  FLOWMACHINE_FLOWDB_USER: # Database user for FlowMachine
    external: true
  FLOWMACHINE_FLOWDB_PASSWORD: # Password for FlowDB
    external: true
  POSTGRES_PASSWORD: # Postgres superuser password
    external: true
  JWT_SECRET_KEY: # Secret used to sign api tokens
    external: true
  REDIS_PASSWORD: # Redis password
    external: true
  FLOWAPI_IDENTIFIER: # Secret used in combination with secret key for decoding JWTs, should be unique per FlowAPI server
    external: true
networks:
  db:
  redis:
  zero:
  api:
services:
    flowdb:
        image: "flowminder/flowdb-testdata:${CIRCLE_BRANCH:-latest}"
        environment:
          - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
        ports:
          - "9000:5432"
        secrets:
          - POSTGRES_PASSWORD
          - FLOWAPI_FLOWDB_USER
          - FLOWAPI_FLOWDB_PASSWORD
          - FLOWMACHINE_FLOWDB_USER
          - FLOWMACHINE_FLOWDB_PASSWORD
        tty: true
        volumes:
          - type: tmpfs
            target: /dev/shm
            tmpfs:
              size: 1000000000
        stdin_open: true
        networks:
          db:
            aliases:
              - flowdb
    flowmachine:
        image: "flowminder/flowmachine:${CIRCLE_BRANCH:-latest}"
        environment:
            - FLOWDB_PORT=5432
            - FLOWDB_HOST=flowdb
            - FLOWMACHINE_LOG_LEVEL=${FLOWMACHINE_LOG_LEVEL:-error}
            - FLOWMACHINE_SERVER_DEBUG_MODE=${FLOWMACHINE_SERVER_DEBUG_MODE:-False}
            - REDIS_HOST=flowmachine_query_locker
        secrets:
          - FLOWMACHINE_FLOWDB_USER
          - FLOWMACHINE_FLOWDB_PASSWORD
          - REDIS_PASSWORD
        networks:
          - db
          - redis
          - zero
    flowapi:
        image: "flowminder/flowapi:${CIRCLE_BRANCH:-latest}"
        ports:
          - "9090:9090"
        environment:
            - FLOWMACHINE_HOST=flowmachine
            - FLOWMACHINE_PORT=5555
            - FLOWDB_HOST=flowdb
            - FLOWDB_PORT=5432
            - FLOWAPI_FLOWDB_USER=flowapi
            - FLOWAPI_LOG_LEVEL=${FLOWAPI_LOG_LEVEL:-error}
        secrets:
          - cert-flowkit.pem
          - JWT_SECRET_KEY
          - FLOWAPI_FLOWDB_USER
          - FLOWAPI_FLOWDB_PASSWORD
          - FLOWAPI_IDENTIFIER
        networks:
          - zero
          - db
          - api
    flowmachine_query_locker:
        image: bitnami/redis:latest
        environment:
          - REDIS_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD
        secrets:
          - REDIS_PASSWORD
        networks:
          redis:
            aliases:
              - redis

